apiVersion: v1
kind: Service
metadata:
    name: "rdnapps-b347"
    labels:
        app: "rdnapps-b347"
spec:
    type: LoadBalancer
    ports:
    - port: 5001
      targetPort: 5001
      protocol: TCP
      name: http
    selector:
        app: "rdnapps-b347"