# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: CI/CD MySelfLog

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'

    - name: Build with dotnet
      run: dotnet build ./src/MySelfLog.Api.sln --configuration Release

    - name: dotnet publish
      run: dotnet publish ./src/MySelfLog.Api.sln -c Release -o ${{env.DOTNET_ROOT}}/myapp

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'myselflog'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_6a6007a280104357b19ca27533ed69aa }}
        package: ${{env.DOTNET_ROOT}}/myapp 
